# Generated by Django 5.0.1 on 2024-02-12 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=255)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erpapp.client')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erpapp.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('building_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Leave_Salary', models.CharField(max_length=255)),
                ('Bonus', models.CharField(max_length=255)),
                ('Overtime', models.CharField(max_length=255)),
                ('Ticket', models.CharField(max_length=255)),
                ('LOP', models.CharField(max_length=255)),
                ('Damage_Deduct', models.CharField(max_length=255)),
                ('other_Deduct', models.CharField(max_length=255)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erpapp.building')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=False)),
                ('abscent', models.BooleanField(default=False)),
                ('reason', models.CharField(max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erpapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectype', models.IntegerField(choices=[(1, 'AMC'), (2, 'LPO'), (3, 'Workloader')])),
                ('cradle_number', models.CharField(max_length=50)),
                ('starting_date', models.DateField()),
                ('finishing_date', models.DateField()),
                ('number_of_days', models.IntegerField()),
                ('team', models.CharField(max_length=255)),
                ('materials_used', models.TextField()),
                ('receipt', models.CharField(max_length=50)),
                ('invoice_number', models.CharField(max_length=50)),
                ('vat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receivable_pending', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comments', models.TextField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erpapp.building')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erpapp.client')),
            ],
        ),
        migrations.CreateModel(
            name='AMC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('yearly_cycle', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erpapp.project')),
            ],
        ),
        migrations.CreateModel(
            name='Supplierproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Starting_Date', models.CharField(max_length=255)),
                ('Finishing_Date', models.CharField(max_length=255)),
                ('No_of_Days', models.CharField(max_length=255)),
                ('LPO', models.CharField(max_length=255)),
                ('Invoice_No', models.CharField(max_length=255)),
                ('VAT', models.CharField(max_length=255)),
                ('Amount', models.CharField(max_length=255)),
                ('Total_Amount', models.CharField(max_length=255)),
                ('payable_Pending', models.CharField(max_length=255)),
                ('Comments', models.CharField(max_length=255)),
                ('paid', models.CharField(max_length=255)),
                ('Building_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erpapp.building')),
                ('supplier_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erpapp.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Workloader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_2', models.CharField(max_length=255)),
                ('normal_3', models.CharField(max_length=255)),
                ('critical', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erpapp.project')),
            ],
        ),
    ]
