# Generated by Django 5.0.1 on 2024-02-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='abscent',
            field=models.BooleanField(default=True),
        ),
    ]
