# Generated by Django 5.0.1 on 2024-03-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attendance_attachments/'),
        ),
    ]
