# Generated by Django 5.0.1 on 2024-03-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='employee_attachments/')),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='attachment',
        ),
        migrations.AddField(
            model_name='employee',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='erpapp.attachment'),
        ),
    ]
