# Generated by Django 5.0.1 on 2024-02-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpapp', '0002_alter_attendance_abscent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='abscent',
        ),
        migrations.AddField(
            model_name='attendance',
            name='absent',
            field=models.BooleanField(default=False),
        ),
    ]
