# Generated by Django 5.0.1 on 2024-03-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpapp', '0004_attachment_remove_employee_attachment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='attachment',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.AddField(
            model_name='employee',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='employee_attachments/'),
        ),
    ]
