# Generated by Django 5.0.1 on 2024-02-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpapp', '0005_remove_workloader_project_project_amc_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='workloader_type',
            field=models.CharField(blank=True, choices=[('Normal 2', 'Normal 2'), ('Normal 3', 'Normal 3'), ('Critical', 'Critical')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='yearly_cycle',
            field=models.CharField(blank=True, choices=[('Yearly 1', 'Yearly 1'), ('Yearly 2', 'Yearly 2'), ('Yearly 3', 'Yearly 3'), ('Yearly 4', 'Yearly 4')], max_length=50, null=True),
        ),
    ]
