# Generated by Django 5.0.1 on 2024-04-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpapp', '0009_remove_employee_attachment_delete_attachment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='attachment',
            new_name='emiratesattachment',
        ),
        migrations.AddField(
            model_name='employee',
            name='operatorcardattachment',
            field=models.FileField(blank=True, null=True, upload_to='employee_attachments/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='passportattachment',
            field=models.FileField(blank=True, null=True, upload_to='employee_attachments/'),
        ),
    ]
